### ISSUE TITLE
Does it works?

### ISSUE THREAD

**Issue by ignaciomarinr** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#13]
Does native messaging works in edge? I've  downloaded this extension and it has been impossible for me making it work. I have no way to check if Edge is establishing communication with the UWP app.

**Comment by sawsonh** [comment]
It is not working for me either.
- In background.js, I receive the exception "Object expected" when executing this line: port = browser.runtime.connectNative("NativeMessagingHostInProcessService");
- In the NativeMessagingHostInProcessService project properties I did check "Do not launch, but debug my code when it starts".  None of my breakpoints are getting hit.

**Comment by leonagase** [comment]
ruitz
