### ISSUE TITLE
The color-changer extension does not work

### ISSUE THREAD

**Issue by jesaremi** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#19]
Just downloaded the samples. Selected color-changer and successfully installed it.
Navigated to https://docs.microsoft.com/en-us
Clicked on Red nothing happened. Clicked on Blue, the same again.
Regardless of many times I uninstall or install or restart my browser it just does not work.
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by libbymc** [comment]
Hi @jesaremi - My team and I are not able to repro your issue on the same build, as well as other EdgeHTML 17+ builds. Verify you're re-navigating to a docs.microsoft.com after you've installed the extension.  Note that this extension only changes the header color.  

Feel free to ping me at work and I'm happy to help troubleshoot!

**Comment by libbymc** [comment]
@jesaremi - would you mind sending along the console logs? This will help us debug further.

**Comment by jesaremi** [comment]
the console has nothing printed . please see the attached screenshot. This is after me clicking "Red".

# #
![capture](https://user-images.githubusercontent.com/22337719/40743033-3ded031a-6405-11e8-90dc-c39534ee5db4.PNG)

**Comment by libbymc** [comment]
@jesaremi - my engineering partners also tried running the code in the same build, and they could not find an issue.  I'll reach out to you at work and we can try to resolve.

**Comment by libbymc** [comment]
Closing - resolved offline. Re-cloning the repo fixed the issue!
