### ISSUE TITLE
Content Script not getting loaded

### ISSUE THREAD

**Issue by jlobello** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#2]
The sample starting page, SecureInput.html, does not match the content_script rules & therefore doesn't get loaded...

    "content_scripts": [
        {
          "matches": ["*://*/secureinput*"],
          "js": ["content.js"],
          "run_at": "document_end"
        }

You can fix this by renaming the starting page or update the matches rule.

**Comment by abbycar** [comment]
I @jlobello!
Could you give a little more info on this issue? 
If you have SecureInput.html open in Edge and deploy the extension from Visual Studio, the extension should be installed and the "Connect" button enabled.

**Comment by jlobello** [comment]
I copied the file to an IIS server & ran it from there over http, hence the case-sensitivity..

**Comment by abbycar** [comment]
Thanks for pointing that out. I've updated the sample so that "SecureInput.html" is now "secureinput.html".
Please let me know if this fixes the issue. :)
