### ISSUE TITLE
Demo extension code not working

### ISSUE THREAD

**Issue by zydjohnHotmail** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#26]
Hello:
I have followed the tutorial: Create an extension tutorial Part 1 & Create an extension tutorial Part 2.
I have tried to load the extension using "Load Unpacked" in both Chrome (Version 89.0.4389.82) and Edge (Version 89.0.774.48) on Windows 10 (Version 20H2).
However on both browsers, I can't show any NASA image, the one downloaded from the URL: https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/blob/master/extension-getting-started-part2/extension-getting-started-part2/images/stars.jpeg
It is not showing.
In order to debug the script, I added one statement in popup\popup.js, so it looks now like:
`C:\Temp>type popup.js

const sendMessageId = document.getElementById("sendmessageid");
if (sendMessageId) {
    console.log('Inside');
    sendMessageId.onclick = function() {
        chrome.tabs.query({ active: true, currentWindow: true }, function(tabs) {
            chrome.tabs.sendMessage(
                tabs[0].id,
                {
                    url: chrome.extension.getURL("images/stars.jpeg"),
                    imageDivId: `${guidGenerator()}`,
                    tabId: tabs[0].id
                },
                function(response) {
                    window.close();
                }
            );
            function guidGenerator() {
                const S4 = function () {
                    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
                };
                return (S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4());
            }
        });
    };
}

C:\Temp>`

But when I open a new tab, in Edge, on the https://www.bing.com/ page, I click on extension icon, I can see message:
Show the NASA picture of the day
(select the image to remove)
Display
But I can't see any picture from the popup.html, and click on "Display" button, I got nothing.
Yet, the worse is: I right click on the "https://www.bing.com/" page, and select "inspect" trying to see any output in "console" tab, I saw nothing. (I should have seen "Inside" on the console tab, right?)
And it is the same as in Chrome browser.
Please check the demo code and let me know if I made any mistake or if there is any mistake in the demo extension code.

**Comment by Reezaali** [comment]
Hi @zydjohnHotmail - sorry to hear about this issue. Please reach out to the Extensions engineering team using the information on this page: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team
