### ISSUE TITLE
The extensions keep bouncing under a specific broswer window size.

### ISSUE THREAD

**Issue by Maigc-Yang** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#27]
The extensions keep bouncing under a specific broswer window size.

https://user-images.githubusercontent.com/14266657/131862721-4c75e54d-5dc0-459c-87e8-533d620f4331.mp4

**Comment by gebansal** [comment]
Thank you @Maigc-Yang for reporting this issue. It's a known bug and is being worked on. It happens at a specific window size and should be fixed in the coming releases.
