### ISSUE TITLE
setBadgeText and setBadgeBackgroundColor not working

### ISSUE THREAD

**Issue by sandeeprawat** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#3]
I am trying to write an extension that sets Badge Text/Color but it doesn't seem to be working on 15031 build. Could you post a working sample for the same? 
Also there seems to be a compatibility issue with the setBadgeBackgroundColor between Edge and Chrome. Chrome works with a Color string e.g. "Red" but Edge API seems to be accepting only an array.

Please take a look.

Thanks

**Comment by smehla** [comment]
Try **browser.browserAction.*** instead **chrome.browserAction.***. It works for me.
![image](https://cloud.githubusercontent.com/assets/7221185/23406125/b6b79a08-fdbd-11e6-88cc-8240e5439027.png)

**Comment by sandeeprawat** [comment]
So it works but only if I provide max 4 character to setBadgeText. Any more characters and it silently ignores it. Slightly different behavior than chrome but works. I would expect it to trim the string though. Hope they fix it in next release.

**Comment by abbycar** [comment]
Hi @sandeeprawat !
We don’t support color names, but we do support arrays and hex values.
I'll add a note about this to the Edge extensions documentation. :)

Here's a sample:

```javascript
browser.browserAction.onClicked.addListener(function() {
    if (toggle) {
        toggle = false;
        browser.browserAction.setBadgeText({
            text:'Hi!'
        });
        browser.browserAction.setBadgeBackgroundColor({
            color: '#FF0000'
        });
    } else {
        toggle = true;
        browser.browserAction.setBadgeText({
            text:'Bye!'
        });
        browser.browserAction.setBadgeBackgroundColor({
            color:'#0000FF'
        });
    }
});
```
