### ISSUE TITLE
can developer use the edge's sidebar?

### ISSUE THREAD

**Issue by GaoCan702** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#36]
i'm very like edge's sidebar, is there some method use sidebar instead of popup page?

**Comment by captainbrosset** [comment]
Sorry about the delay replying. This repository hasn't been monitored in a long time and the sample code here isn't used anymore.
Here is our new Microsoft Edge extensions repository where you can reach out to the team: https://github.com/microsoft/MicrosoftEdge-Extensions

The answer your question though: yes, you can create extensions that make use of the sidebar in Edge. Here's how: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/sidebar
