### ISSUE TITLE
How  to hide "SecureInput" from start menu?

### ISSUE THREAD

**Issue by hdmyt** [MicrosoftEdge/MicrosoftEdge-Extensions-Demos#4]
I created "SecureInput" appx package and installed it.
"SecureInput" shows in the start menu and it can be clicked.
I want to hide it, because "SecureInput" is background app and not need to be clicked.
How  to hide "SecureInput"?

**Comment by abbycar** [comment]
Hi @hdmyt !
In your `Package.appxmanifest` file you can add `AppListEntry="none"` to the `VisualElements` element.

For this example we'd then have:

```
<uap:VisualElements AppListEntry="none" DisplayName="SecureInput" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="NativeMessagingHostInProcess" BackgroundColor="transparent">
```

**Comment by spineltwin** [comment]
Hi @abbycar !
I was able to hide "Secure Input".
Thank you for your reply.

**Comment by hdmyt** [comment]
Hi @abbycar .
I was able to hide "Secure Input".
Thank you for your reply.
